# Site settings
title: Dear Pastor's Wife | A haven for pastors' wives
description: "A blog for pastors' wives; a place to connect and receive encouragement."
url: "http://pastormay.github.io/dearpastorswife"
author:
  name: "Pastor May Ijisesan"
  email: "dearpastorswife@gmail.com"
  url: "http://www.pastormay.org"

# Build settings
baseurl: /dearpastorswife/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
